platform :ios, '9.0'

target 'Password Manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Password Manager

    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'


  target 'Password ManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Password ManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
